version: '3'
services:

  database:
    image: kdpsc/pd-data:v1.0
    container_name: database
    restart: unless-stopped
  
  backend:
    image: kdpsc/pd-app:v1.0
    container_name: backend
    restart: unless-stopped
  
  frontend:
    image: kdpsc/pd-proxy:v1.0
    container_name: frontend
    restart: unless-stopped
    ports:
      - 80:80
  